//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TProductos()
        {
            this.TOrdenes = new HashSet<TOrdenes>();
        }
    
        public long ConProductos { get; set; }
        public string NombreProducto { get; set; }
        public long ConProovedores { get; set; }
        public long ConCategoria { get; set; }
        public decimal Precio { get; set; }
        public int TotalUnidades { get; set; }
    
        public virtual TCategoria TCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrdenes> TOrdenes { get; set; }
        public virtual TProovedores TProovedores { get; set; }
    }
}
