//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUsuario()
        {
            this.TOrdenes = new HashSet<TOrdenes>();
        }
    
        public long ConUsuario { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contrasenna { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Canton { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public bool Estado { get; set; }
        public long ConRol { get; set; }
        public long ConProvincia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrdenes> TOrdenes { get; set; }
        public virtual TProvincia TProvincia { get; set; }
        public virtual TRoles TRoles { get; set; }
    }
}
